services:
  - type: web
    name: taskaeroleads-backend
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn main:main_app --config gunicorn_config.py --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.11

